### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by akrueger90** [JakubMifek/SelectTransform#22]
Hello, 

found this because the original stjs seems to be incompatible with React Native. 
Sadly this also applies for this module. 

When I simply add the example code to an React Native App I always get the error 

Unhandled promise rejection [Error: Expression contained unresolvable expressions -- 1:14:invalid statement encountered. -- {{ name }} -- 1:14:invalid statement encountered.]

In other environments everything is working as expected.

**Comment by JakubMifek** [comment]
Hello @akrueger90,
thank you for bringing this to my attention. ST.js started as a part of a FE framework and I would love for it to continue being a useful tool in that area.

That being said, I am, sadly, not familiar with most of FE development frameworks and have zero knowledge about React. Could you perhaps link me some kind of an example application that I could run in somewhat simple manner (ideally with exact instructions on how to reproduce the issue) so that I don't have to study-up on how the framework works?

**Comment by akrueger90** [comment]
Hey, 

the issue is not directly linked to React Native. 
It is related to the hermes js engine which can be enabled. 

So the quick fix is to disable hermes for now. 
I guess this is more a hermes then a selecttransform bug. 

Thanks for the quick reply

**Comment by akrueger90** [comment]
quick followup. 
It looks like the problem is the usage of the legacy "with" statement
https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-with-statement

I tried simply replacing 
`func = Function("with(this) {return (" + slot + ")}").bind(data);`
by 
`func = Function("return this." + slot).bind(data);`
and it works. Maybe there is a more robust way to handle this

**Comment by JakubMifek** [comment]
I see, that might be an issue. Original STJS implementation uses this to enable user to write whole JS statements and functions inside of the templates. The `with` statement enables the user to not only access properties inside of `this` object but also all the global properties.

For example in the line:
`func = Function('with(this) {${slot}}').bind(data);`

the `slot` variable might be whatever javascript expression containing a return statement. So even:
`return Object.keys(someProperty).filter(...)`
should be applicable.

Trying to find the property name in the statement is imho impossible (or at least in an effective manner). So from my POV I have two options:
1. Leave as is
2. Forbid complicated expressions and try to compensate using the STJS framework and its functions

I will try to think about this once I have time to play around with the code a bit more in-depth.

If you have any more inputs on this, let me know :)
